In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import  MinMaxScaler

In [5]:
data = np.random.randint(0,100,(10,2))

In [6]:
data

array([[34, 83],
       [50, 87],
       [15,  2],
       [58, 62],
       [91, 86],
       [11, 18],
       [54, 98],
       [68, 28],
       [37, 50],
       [25, 10]])

In [7]:
scalerModel = MinMaxScaler()

In [8]:
type(scalerModel)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scalerModel.fit(data)

//anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scalerModel.transform(data)

array([[0.2875    , 0.84375   ],
       [0.4875    , 0.88541667],
       [0.05      , 0.        ],
       [0.5875    , 0.625     ],
       [1.        , 0.875     ],
       [0.        , 0.16666667],
       [0.5375    , 1.        ],
       [0.7125    , 0.27083333],
       [0.325     , 0.5       ],
       [0.175     , 0.08333333]])

In [11]:
# if u want to do. both of them together
scalerModel.fit_transform(data)

//anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

array([[0.2875    , 0.84375   ],
       [0.4875    , 0.88541667],
       [0.05      , 0.        ],
       [0.5875    , 0.625     ],
       [1.        , 0.875     ],
       [0.        , 0.16666667],
       [0.5375    , 1.        ],
       [0.7125    , 0.27083333],
       [0.325     , 0.5       ],
       [0.175     , 0.08333333]])

In [12]:
import pandas as pd

In [16]:
data = pd.DataFrame(data= np.random.randint(0,100,(50,4)), columns=['f1', 'f2', 'f3', 'label'])

In [17]:
data

    f1  f2  f3  label
0   40  52  62     63
1   71  58  18     96
2   16  34  72      9
3   56  50  40     37
4    9  98  60     42
5   72  84  93     97
6   20  68  50     36
7   41  82  88     85
8   92  92   3     45
9   88  32  24      0
10  69  71  98     53
11  88  21   1     39
12  43  83  46     83
13  50  64  76     63
14  81  44  90     84
15  27  58  54     16
16   1  87  56     43
17  50  29  65      1
18  92  70  90     99
19  31  97  59     18
20  24   4  16     78
21  83  35  93     66
22  57  56  44     68
23  60  57   5     37
24  87  21  71      4
25  30  49  37     41
26  96  80  80      9
27   5   1  12     96
28  38  32  62     74
29  17  90   4     21
30  66   1  82     67
31  93  53  90     36
32  27  29  51      2
33  61  25  84     88
34  58  75  92      9
35  42  23  62     80
36  71  98  96     69
37  72  77  71     30
38   3  35  14      0
39  49  70  91     62
40  98  11   4     81
41  30  38  20     67
42   3  35   4     93
43  26  88  55      7
44  52  40  79      8
45  45  92  61     61
46  24  82  58     34
47  92  86  98     37
48   8  54  26     25
49   4  74  45     12

In [18]:
X = data[['f1','f2','f3']]

In [19]:
X

    f1  f2  f3
0   40  52  62
1   71  58  18
2   16  34  72
3   56  50  40
4    9  98  60
5   72  84  93
6   20  68  50
7   41  82  88
8   92  92   3
9   88  32  24
10  69  71  98
11  88  21   1
12  43  83  46
13  50  64  76
14  81  44  90
15  27  58  54
16   1  87  56
17  50  29  65
18  92  70  90
19  31  97  59
20  24   4  16
21  83  35  93
22  57  56  44
23  60  57   5
24  87  21  71
25  30  49  37
26  96  80  80
27   5   1  12
28  38  32  62
29  17  90   4
30  66   1  82
31  93  53  90
32  27  29  51
33  61  25  84
34  58  75  92
35  42  23  62
36  71  98  96
37  72  77  71
38   3  35  14
39  49  70  91
40  98  11   4
41  30  38  20
42   3  35   4
43  26  88  55
44  52  40  79
45  45  92  61
46  24  82  58
47  92  86  98
48   8  54  26
49   4  74  45

y = data['label']

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [24]:
X_train.shape

(33, 3)

In [25]:
X_test.shape

(17, 3)